name: Windows CI
on: [pull_request]

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.9.1'

    - name: Install Visual Studio components
      shell: powershell
      run: .\.github\workflows\scripts\install-vs-features.ps1 Microsoft.VisualStudio.Component.VC.v141.x86.x64,Microsoft.VisualStudio.ComponentGroup.UWP.VC.v141

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: 16.5
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Install node modules
      run: yarn install
 
    - name: NuGet restore
      run: nuget restore windows\DatePickerTest.sln

    - name: Build x64 Debug
      run: msbuild windows\DatePickerTest.sln /p:Configuration=Debug /p:Platform=x64 -m